version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-master:/var/lib/mysql
      - ./master-init:/docker-entrypoint-initdb.d
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-slave-updates=ON
      --binlog-group-commit-sync-delay=1000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3

  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    restart: unless-stopped
    depends_on:
      mysql-master:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-slave1:/var/lib/mysql
      - ./slave1-init:/docker-entrypoint-initdb.d
    command:
      --server-id=2
      --relay-log=relay-log
      --read-only=1
      --skip-slave-start
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-bin=mysql-bin

  mysql-slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    restart: unless-stopped
    depends_on:
      mysql-master:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-slave2:/var/lib/mysql
      - ./slave2-init:/docker-entrypoint-initdb.d
    command:
      --server-id=3
      --relay-log=relay-log
      --read-only=1
      --skip-slave-start
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-bin=mysql-bin
